# Sandbox

In [1]:
%load_ext jupyter_black
%load_ext autoreload
%autoreload 2

In [30]:
import ocha_stratus as stratus
import pandas as pd

from src.utils.timeseries import detrend_column
from src.utils.rp_calc import calculate_one_group_rp

In [3]:
query = """
SELECT *
FROM public.seas5
WHERE pcode = 'SO'
"""

In [7]:
df = pd.read_sql(
    query,
    stratus.get_engine(stage="prod"),
    parse_dates=["valid_date", "issued_date"],
)

In [5]:
df

,iso3,pcode,valid_date,issued_date,leadtime,adm_level,mean,median,min,max,count,sum,std
0,SOM,SO,1991-08-01,1991-08-01,0,0,0.408863,0.213034,0.013126,3.306107,20676,8453.6590,0.521375
1,SOM,SO,1991-08-01,1991-07-01,1,0,0.329535,0.189156,0.014192,2.112049,20676,6813.4590,0.335994
2,SOM,SO,1991-08-01,1991-06-01,2,0,0.338107,0.178797,0.002777,2.226891,20676,6990.7080,0.387419
3,SOM,SO,1991-08-01,1991-05-01,3,0,0.304106,0.156325,0.004948,2.195641,20676,6287.6973,0.352408
4,SOM,SO,1991-08-01,1991-04-01,4,0,0.292625,0.141966,0.003313,2.324412,20676,6050.3047,0.358042
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3747,SOM,SO,2025-10-01,2025-08-01,2,0,1.361580,1.261131,0.256190,3.577864,20676,28152.0210,0.737426
3748,SOM,SO,2025-11-01,2025-08-01,3,0,1.161147,0.813266,0.167700,4.682526,20676,24007.8830,0.884882
3749,SOM,SO,2025-12-01,2025-08-01,4,0,0.412079,0.251531,0.039641,2.819808,20676,8520.1480,0.404910
3750,SOM,SO,2026-01-01,2025-08-01,5,0,0.090552,0.044498,0.003562,1.696177,20676,1872.2588,0.130859
3751,SOM,SO,2026-02-01,2025-08-01,6,0,0.068829,0.042082,0.004622,1.079182,20676,1423.1052,0.079916

In [37]:
issued_month = 8
# valid_months = [10, 11, 12]
valid_months = [11, 12, 1]

In [38]:
df_issue = (
    df[
        df["valid_date"].dt.month.isin(valid_months)
        & (df["issued_date"].dt.month == issued_month)
    ]
    .groupby(df["issued_date"].dt.year)["mean"]
    .mean()
    .rename_axis("year")
    .reset_index()
)

In [39]:
df_issue = detrend_column(df_issue, col="mean", index_col="year")

In [40]:
df_issue

    year      mean  mean_detrended
0   1981  0.641801        0.648619
1   1982  0.950034        0.956542
2   1983  0.586856        0.593054
3   1984  0.580985        0.586874
4   1985  0.582941        0.588519
5   1986  0.712863        0.718131
6   1987  0.764532        0.769491
7   1988  0.486425        0.491074
8   1989  0.608558        0.612897
9   1990  0.655173        0.659202
10  1991  0.696184        0.699903
11  1992  0.638500        0.641909
12  1993  0.746075        0.749174
13  1994  1.320464        1.323253
14  1995  0.665132        0.667611
15  1996  0.537787        0.539957
16  1997  2.193139        2.194999
17  1998  0.492238        0.493788
18  1999  0.504121        0.505361
19  2000  0.524296        0.525226
20  2001  0.559822        0.560442
21  2002  0.845498        0.845808
22  2003  0.584380        0.584380
23  2004  0.836370        0.836060
24  2005  0.732649        0.732029
25  2006  1.103234        1.102304
26  2007  0.616194        0.614954
27  2008  0.488986        0.487437
28  2009  0.815474        0.813615
29  2010  0.596393        0.594223
30  2011  0.842821        0.840342
31  2012  0.822454        0.819664
32  2013  0.494533        0.491434
33  2014  0.766016        0.762607
34  2015  1.047706        1.043987
35  2016  0.531912        0.527883
36  2017  0.667923        0.663584
37  2018  0.668021        0.663372
38  2019  1.047046        1.042087
39  2020  0.545982        0.540713
40  2021  0.527095        0.521516
41  2022  0.454499        0.448611
42  2023  1.439117        1.432919
43  2024  0.583538        0.577030
44  2025  0.554593        0.547775

In [41]:
df_issue = calculate_one_group_rp(df_issue, col_name="mean", ascending=True)
df_issue = calculate_one_group_rp(
    df_issue, col_name="mean_detrended", ascending=True
)

In [42]:
df_issue.sort_values("mean_rank")

,year,mean,mean_detrended,mean_rank,mean_rp,mean_detrended_rank,mean_detrended_rp
41,2022,0.454499,0.448611,1.0,46.000000,1.0,46.000000
7,1988,0.486425,0.491074,2.0,23.000000,3.0,15.333333
27,2008,0.488986,0.487437,3.0,15.333333,2.0,23.000000
17,1998,0.492238,0.493788,4.0,11.500000,5.0,9.200000
32,2013,0.494533,0.491434,5.0,9.200000,4.0,11.500000
18,1999,0.504121,0.505361,6.0,7.666667,6.0,7.666667
19,2000,0.524296,0.525226,7.0,6.571429,8.0,5.750000
40,2021,0.527095,0.521516,8.0,5.750000,7.0,6.571429
35,2016,0.531912,0.527883,9.0,5.111111,9.0,5.111111
15,1996,0.537787,0.539957,10.0,4.600000,10.0,4.600000
39,2020,0.545982,0.540713,11.0,4.181818,11.0,4.181818
44,2025,0.554593,0.547775,12.0,3.833333,12.0,3.833333
20,2001,0.559822,0.560442,13.0,3.538462,13.0,3.538462
3,1984,0.580985,0.586874,14.0,3.285714,16.0,2.875000
4,1985,0.582941,0.588519,15.0,3.066667,17.0,2.705882
43,2024,0.583538,0.577030,16.0,2.875000,14.0,3.285714
22,2003,0.584380,0.584380,17.0,2.705882,15.0,3.066667
2,1983,0.586856,0.593054,18.0,2.555556,18.0,2.555556
29,2010,0.596393,0.594223,19.0,2.421053,19.0,2.421053
8,1989,0.608558,0.612897,20.0,2.300000,20.0,2.300000
26,2007,0.616194,0.614954,21.0,2.190476,21.0,2.190476
11,1992,0.638500,0.641909,22.0,2.090909,22.0,2.090909
0,1981,0.641801,0.648619,23.0,2.000000,23.0,2.000000
9,1990,0.655173,0.659202,24.0,1.916667,24.0,1.916667
14,1995,0.665132,0.667611,25.0,1.840000,27.0,1.703704
36,2017,0.667923,0.663584,26.0,1.769231,26.0,1.769231
37,2018,0.668021,0.663372,27.0,1.703704,25.0,1.840000
10,1991,0.696184,0.699903,28.0,1.642857,28.0,1.642857
5,1986,0.712863,0.718131,29.0,1.586207,29.0,1.586207
24,2005,0.732649,0.732029,30.0,1.533333,30.0,1.533333
12,1993,0.746075,0.749174,31.0,1.483871,31.0,1.483871
6,1987,0.764532,0.769491,32.0,1.437500,33.0,1.393939
33,2014,0.766016,0.762607,33.0,1.393939,32.0,1.437500
28,2009,0.815474,0.813615,34.0,1.352941,34.0,1.352941
31,2012,0.822454,0.819664,35.0,1.314286,35.0,1.314286
23,2004,0.836370,0.836060,36.0,1.277778,36.0,1.277778
30,2011,0.842821,0.840342,37.0,1.243243,37.0,1.243243
21,2002,0.845498,0.845808,38.0,1.210526,38.0,1.210526
1,1982,0.950034,0.956542,39.0,1.179487,39.0,1.179487
38,2019,1.047046,1.042087,40.0,1.150000,40.0,1.150000
34,2015,1.047706,1.043987,41.0,1.121951,41.0,1.121951
25,2006,1.103234,1.102304,42.0,1.095238,42.0,1.095238
13,1994,1.320464,1.323253,43.0,1.069767,43.0,1.069767
42,2023,1.439117,1.432919,44.0,1.045455,44.0,1.045455
16,1997,2.193139,2.194999,45.0,1.022222,45.0,1.022222